install:
  - sudo apt-get update -qq
  - sudo apt-get install python-pip curl -y
  - sudo pip install pelican markdown
  - pip install Fabric

script:
  - hostname
  - curl http://169.254.169.254/latest/meta-data/public-ipv4
  - make html
  - make serve

